[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
homepage = "https://gitlab.com/zillowe/app"
repository = "https://gitlab.com/zillowe/app"
documentation = "https://docs.rs/app/latest/app"
keywords = ["rust", "template"]
description = "Rename me."

[workspace.lints.rust]
unreachable_pub = "warn"
missing_docs = "deny"

[workspace.lints.clippy]
missing_docs_in_private_items = "deny"
undocumented_unsafe_blocks = "deny"
unwrap_used = "deny"
todo = "deny"
indexing_slicing = "warn"
cloned_instead_of_copied = "warn"
inefficient_to_string = "warn"
explicit_iter_loop = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
naive_bytecount = "warn"
pedantic = { level = "warn", priority = -1 }
too_many_arguments = "allow"
type_complexity = "allow"
must_use_candidate = "allow"
cast_possible_truncation = "allow"
too_many_lines = "allow"
struct_excessive_bools = "allow"
fn_params_excessive_bools = "allow"
ref_option = "allow"
cast_precision_loss = "allow"
cast_possible_wrap = "allow"

[workspace.dependencies]

